[package]
name = "onoff_light"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "matter_bin"
path = "src/main.rs"

[dependencies]
matter = {path = "../../matter"}
log = {version = "0.4.14", features = ["max_level_info", "release_max_level_warn"]}
env_logger = "0.9.0"
